131780323_methods_and_recursion_master
votillev717/learning_by_doing pull request #2
Opened 2016-10-14 03:12 UTC by votillev717

2016-10-15 02:25 UTC, jasonnoble requested changes

2016-10-15 02:25 UTC, jasonnoble commented on methods_and_recursion/bottles_of_beer.rb
> +#!usr/bin/env ruby
`#!/usr/bin/env ruby` (missing a slash)

2016-10-15 02:25 UTC, jasonnoble commented on methods_and_recursion/bottles_of_beer.rb
> +def bottles_of_beer
What's this method do?

2016-10-15 02:25 UTC, jasonnoble commented on methods_and_recursion/bottles_of_beer.rb
> +  puts "#{number_of_bottles2} bottles of beer on the wall.
`puts "#{number_of_bottles2} bottles of beer on the wall.\n\n"`

2016-10-25 06:44 UTC, votillev717 commented on methods_and_recursion/bottles_of_beer.rb
> +#!usr/bin/env ruby
Ok.

2016-10-25 06:44 UTC, votillev717 commented on methods_and_recursion/bottles_of_beer.rb
> +def bottles_of_beer
Not sure.

2016-10-25 06:44 UTC, votillev717 commented on methods_and_recursion/bottles_of_beer.rb
> +  puts "#{number_of_bottles2} bottles of beer on the wall.
Ok.

2016-11-24 01:07 UTC, closed without merging